name: Slither

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.6
      SOLC_VERSION: v0.5.17
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${PYTHON_VERSION}
      - name: Install Solidity
        run: |
          wget https://github.com/ethereum/solidity/releases/download/${SOLC_VERSION}/solc-static-linux
          chmod 755 solc-static-linux
          sudo mv solc-static-linux /usr/local/bin
          sudo ln -s -f /usr/local/bin/solc-static-linux /usr/local/bin/solc
      - name: Install Slither
        run: pip3 install slither-analyzer
      - name: Run Slither
        run: cd solidity && slither .